spring:
  datasource:
    url: jdbc:mariadb://playdata4.iptime.org:8006/team2_auth
    username: team2
    password: team2pass!@#
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: never

  h2:
    console:
      enabled: true
      path: /h2-console

  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:

server:
  port: 8011

jwt:
  rsa:
    private-key-path: ${JWT_RSA_PRIVATE_KEY_PATH}
    public-key-path: ${JWT_RSA_PUBLIC_KEY_PATH}
  issuer: ${JWT_ISSUER:team2-auth}


auth:
  cookie:
    secure: false  # 개발 환경(http)에서 쿠키 전달 허용
